# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Build', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfile',
            name='uploadTime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='clausefile',
            name='uploadTime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ratefile',
            name='uploadTime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
