# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Build', '0002_auto_20170511_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfile',
            name='IsCheckPass',
            field=models.BooleanField(default=0, verbose_name='\u521d\u5ba1\u662f\u5426\u901a\u8fc7'),
        ),
        migrations.AddField(
            model_name='clausefile',
            name='IsCheckPass',
            field=models.BooleanField(default=0, verbose_name='\u521d\u5ba1\u662f\u5426\u901a\u8fc7'),
        ),
        migrations.AddField(
            model_name='ratefile',
            name='IsCheckPass',
            field=models.BooleanField(default=0, verbose_name='\u521d\u5ba1\u662f\u5426\u901a\u8fc7'),
        ),
        migrations.AlterField(
            model_name='ratefile',
            name='IsCheck',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u521d\u5ba1\u901a\u8fc7'),
        ),
    ]
